# Generated by Django 2.1.1 on 2018-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
